import javax.swing.JOptionPane;

/**
 * Classe que cria um formulário para o cadastro de novos Carros.
 * 
 * @author Luan
 * @author Matheo
 */
public class FormularioCarro extends javax.swing.JFrame {

    /**
     * Construtor da classe FormularioCarro
     * Creates new form FormularioCarro
     */
    public FormularioCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldCor = new javax.swing.JTextField();
        jTextFieldRenavam = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter renavam= new javax.swing.text.MaskFormatter("#########");
            jTextFieldRenavam = new javax.swing.JFormattedTextField(renavam);
        }
        catch (Exception e){
        }
        jTextFieldMinimo = new javax.swing.JTextField();
        jTextFieldDiaria = new javax.swing.JTextField();
        jTextFieldMulta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setText("Marca:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 40, 60, 23);

        jLabel3.setText("Modelo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 80, 57, 26);

        jLabel4.setText("Cor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 110, 70, 40);

        jLabel5.setText("Renavam:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 150, 90, 30);

        jLabel6.setText("Dias mínimos de aluguel:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 200, 180, 24);

        jLabel7.setText("Preço da diária (R$):");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 260, 150, 14);

        jLabel8.setText("Multa diária (R$):");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 310, 140, 14);
        jPanel1.add(jTextFieldMarca);
        jTextFieldMarca.setBounds(170, 30, 140, 30);
        jPanel1.add(jTextFieldModelo);
        jTextFieldModelo.setBounds(170, 70, 140, 30);
        jPanel1.add(jTextFieldCor);
        jTextFieldCor.setBounds(170, 110, 140, 30);
        jPanel1.add(jTextFieldRenavam);
        jTextFieldRenavam.setBounds(170, 150, 140, 30);

        jTextFieldMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinimoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMinimo);
        jTextFieldMinimo.setBounds(170, 200, 137, 30);

        jTextFieldDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiariaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDiaria);
        jTextFieldDiaria.setBounds(170, 250, 137, 30);

        jTextFieldMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMultaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMulta);
        jTextFieldMulta.setBounds(170, 300, 137, 30);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 340, 100, 40);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 340, 90, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 60, 680, 420);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de carros");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 720, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiariaActionPerformed

    private void jTextFieldMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinimoActionPerformed
    /**
     * Método que adiciona o Carro descrito nos campos de texto à lista de carros, verificando antes se 
     * este carro não foi previamente adicionado, através de seu Renavam.
     * @param evt ato de selecionar o botão de Salvar
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int flag = 0;
        for (int i = 0; i < ListaCarros.listaCarros.size(); i++)
        {
            if (jTextFieldRenavam.getText().equals(ListaCarros.listaCarros.get(i).getRenavam()))
            {
                JOptionPane.showMessageDialog(null,"Carro já cadastrado.","Aviso",JOptionPane.WARNING_MESSAGE);
                flag++;
                jTextFieldMarca.setText("");
                jTextFieldModelo.setText("");
                jTextFieldCor.setText("");
                jTextFieldRenavam.setText("");
                jTextFieldMinimo.setText("");
                jTextFieldDiaria.setText("");
                jTextFieldMulta.setText("");
            }
        }
        
        if (flag == 0) {
            try {
                if (Integer.parseInt(jTextFieldMinimo.getText()) > 0) {            
            try {
                if (Double.parseDouble(jTextFieldDiaria.getText()) > 0) {
                    try {
                        if (Double.parseDouble(jTextFieldMulta.getText()) > 0.0) {
                    Carro objC = new Carro (jTextFieldMarca.getText(), jTextFieldModelo.getText(), jTextFieldCor.getText(), jTextFieldRenavam.getText(), Integer.parseInt(jTextFieldMinimo.getText()), Double.parseDouble(jTextFieldDiaria.getText()), Double.parseDouble(jTextFieldMulta.getText()));
                    ListaCarros.listaCarros.add(objC);
                    JOptionPane.showMessageDialog(this, "Carro cadastrado com sucesso!"); 

                    jTextFieldMarca.setText("");
                    jTextFieldModelo.setText("");
                    jTextFieldCor.setText("");
                    jTextFieldRenavam.setText("");
                    jTextFieldMinimo.setText("");
                    jTextFieldDiaria.setText("");
                    jTextFieldMulta.setText("");
               
            }   else {
                    JOptionPane.showMessageDialog(null,"Preço da multa inválido. 1","Aviso",JOptionPane.WARNING_MESSAGE);
                    jTextFieldMulta.setText("");
                }
            } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null,"Preço da multa inválido.","Aviso",JOptionPane.WARNING_MESSAGE);
                    jTextFieldMulta.setText("");
            } } else {
                    JOptionPane.showMessageDialog(null,"Preço de aluguel diário inválido.","Aviso",JOptionPane.WARNING_MESSAGE);
                    jTextFieldDiaria.setText("");
                }
            } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null,"Preço de aluguel diário inválido.","Aviso",JOptionPane.WARNING_MESSAGE);
                    jTextFieldDiaria.setText("");
            } } else {
                    JOptionPane.showMessageDialog(null,"Número de dias inválido.","Aviso",JOptionPane.WARNING_MESSAGE);
                    jTextFieldMinimo.setText("");
                }
            } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null,"Número de dias inválido.","Aviso",JOptionPane.WARNING_MESSAGE);
                    jTextFieldMinimo.setText("");
            } }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Método que fecha a tela FormularioCarro.
     * @param evt ato de selecionar o botão Voltar
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMultaActionPerformed

    /**
     * Método principal da classe FormularioCarro
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldDiaria;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMinimo;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldMulta;
    private javax.swing.JTextField jTextFieldRenavam;
    // End of variables declaration//GEN-END:variables
}
