import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 * Classe que gera um formulário para a adição de novos funcionários, através de informações obtidas
 * pelos campos de texto.
 * 
 * @author Luan
 * @author Matheo
 */
public class FormularioFuncionario extends javax.swing.JFrame {

    /**
     * Construtor da Classe FormularioFuncionario
     * Creates new form FormularioFuncionario
     */
    public FormularioFuncionario() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelNascimento = new javax.swing.JLabel();
        jLabelDocumento = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##)#####-####");
            jTextFieldTelefone = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        jTextFieldCPF = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("###.###.###-##");
            jTextFieldCPF = new javax.swing.JFormattedTextField(cpf);
        }
        catch (Exception e){
        }
        jTextFieldNascimento = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            jTextFieldNascimento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabelSexo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonVolta = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 510));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de funcionários");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(250, 0, 206, 30);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 30);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabelNome.setText("Nome:");
        jPanel1.add(jLabelNome);
        jLabelNome.setBounds(50, 50, 60, 23);

        jLabelNascimento.setText("Data de Nascimento:");
        jPanel1.add(jLabelNascimento);
        jLabelNascimento.setBounds(50, 200, 140, 23);

        jLabelDocumento.setText("Número de CPF: ");
        jPanel1.add(jLabelDocumento);
        jLabelDocumento.setBounds(40, 150, 119, 23);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 360, 80, 40);

        jLabelTelefone.setText("Telefone: ");
        jPanel1.add(jLabelTelefone);
        jLabelTelefone.setBounds(40, 110, 70, 23);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(110, 50, 181, 30);

        jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(110, 100, 180, 30);
        jPanel1.add(jTextFieldCPF);
        jTextFieldCPF.setBounds(140, 150, 150, 30);

        jTextFieldNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNascimento);
        jTextFieldNascimento.setBounds(180, 200, 110, 30);

        jLabelSexo.setText("Sexo: ");
        jPanel1.add(jLabelSexo);
        jLabelSexo.setBounds(50, 260, 60, 14);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(579, 216, 225, 0);

        jLabel3.setText("Login:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 320, 50, 20);

        jLabel4.setText("Senha:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 320, 80, 14);

        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldLogin);
        jTextFieldLogin.setBounds(110, 310, 158, 30);

        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(390, 310, 144, 30);

        jButtonVolta.setText("Voltar");
        jButtonVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolta);
        jButtonVolta.setBounds(540, 360, 80, 40);

        jRadioButton1.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Masculino");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(110, 260, 110, 23);

        jRadioButton2.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Feminino");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(220, 260, 120, 23);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(17, 50, 680, 440);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 720, 510);

        setSize(new java.awt.Dimension(719, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNascimentoActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed

    /**
     * Método que, após verificar se o CPF e a data de nascimento informados são válidos, cria um novo objeto do tipo
     * Funcionário e adiciona tal Funcionário à lista de funcionários, verificando também se este 
     * não foi previamente adicionado, através de seu CPF 
     * @param evt seleção do botão Salvar.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int flag = 0;
        try{
            if (jRadioButton1.isSelected() || jRadioButton2.isSelected())
                {
                    if (FormularioCliente.validarCPF(jTextFieldCPF.getText()))
                    {
                        if (FormularioCliente.validarData(jTextFieldNascimento.getText()) && FormularioCliente.confereData(new SimpleDateFormat("dd/MM/yyyy").parse(jTextFieldNascimento.getText())))
                        {
                            for (int i = 0; i < ListaFuncionarios.listaFuncionarios.size(); i++)
                            {
                                if (jTextFieldCPF.getText().equals(ListaFuncionarios.listaFuncionarios.get(i).getDocumento()))
                                {
                                    JOptionPane.showMessageDialog(null,"Funcionário já cadastrado.","Aviso",JOptionPane.WARNING_MESSAGE);
                                    flag++;
                                    jTextFieldNome.setText("");
                                    jTextFieldTelefone.setText("");
                                    jTextFieldCPF.setText("");
                                    jTextFieldNascimento.setText("");
                                    buttonGroup1.clearSelection();
                                }
                            }
                            if (flag == 0) {
                            if (jRadioButton1.isSelected())
                            {
                                Funcionario objF = new Funcionario (jTextFieldNome.getText(), jTextFieldTelefone.getText(), jTextFieldCPF.getText(), jTextFieldNascimento.getText(), "Masculino", jTextFieldLogin.getText(), jPasswordFieldSenha.getText());
                                ListaFuncionarios.listaFuncionarios.add(objF);
                                JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!"); 
                            } else {
                                Funcionario objF = new Funcionario (jTextFieldNome.getText(), jTextFieldTelefone.getText(), jTextFieldCPF.getText(), jTextFieldNascimento.getText(), "Feminino", jTextFieldLogin.getText(), jPasswordFieldSenha.getText());
                                ListaFuncionarios.listaFuncionarios.add(objF);
                                JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!"); 
                            }

                            jTextFieldNome.setText("");
                            jTextFieldTelefone.setText("");
                            jTextFieldCPF.setText("");
                            jTextFieldNascimento.setText("");
                            jTextFieldLogin.setText("");
                            buttonGroup1.clearSelection();
                            jPasswordFieldSenha.setText("");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null,"Data de nascimento inválida.","Aviso",JOptionPane.WARNING_MESSAGE);
                            jTextFieldNascimento.setText("");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null,"CPF inválido.","Aviso",JOptionPane.WARNING_MESSAGE);
                        jTextFieldCPF.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null,"Selecione uma opção para o sexo.","Aviso",JOptionPane.WARNING_MESSAGE);
                }
        }catch(ParseException pe){
            System.err.println(pe);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    /**
     * Método que fecha a tela FormularioFuncionario
     * @param evt seleção do botão Voltar
     */
    private void jButtonVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltaActionPerformed

    /**
     * Método principal da classe FormularioFuncionario
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioFuncionario().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonVolta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelNascimento;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNascimento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
