import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * Classe que apresenta uma tela para alterar os parâmetros de aluguel de um carro
 * que não está alugado
 * 
 * @author Matheo
 */
public class OpcoesCarro extends javax.swing.JFrame {

    public int index;
    
    /**
     * Construtor da classe OpcoesCarros
     */
    public OpcoesCarro() {
        initComponents();
        jPanel1.setVisible(false);
        
    }
    
    /**
     * Método que define a posição do carro selecionado na lista de carros
     * @param index posição do carro na lista de carros
     */
    public void setIndex(int index){
        this.index = index;
    }
    
    /**
     * Método que retorna a posição, na lista que contém os carros, 
     * do carro selecionado na tabela
     * @return a posição do carro na lista de carros
     */
    public int getIndex(){
        return index;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldDias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDiaria = new javax.swing.JTextField();
        jTextFieldMulta = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonAlterar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(494, 320));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);
        jPanel1.add(jTextFieldDias);
        jTextFieldDias.setBounds(120, 20, 130, 30);

        jLabel6.setText("Dias Mínimos:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 30, 90, 14);

        jLabel7.setText("Preço da diária (R$):");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 70, 120, 14);

        jLabel8.setText("Multa diária (R$):");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 110, 150, 14);

        jTextFieldDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiariaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDiaria);
        jTextFieldDiaria.setBounds(120, 60, 130, 30);
        jPanel1.add(jTextFieldMulta);
        jTextFieldMulta.setBounds(120, 100, 130, 30);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(305, 141, 63, 23);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(12, 103, 470, 200);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("O que deseja fazer?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 500, 30);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(null);

        jButtonAlterar.setText("Alterar informações");
        jButtonAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlterarMouseClicked(evt);
            }
        });
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAlterar);
        jButtonAlterar.setBounds(50, 10, 150, 30);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonCancelar);
        jButtonCancelar.setBounds(320, 10, 90, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 40, 470, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que, quando o carro selecionado não estiver alugado, abre uma tela que
     * dá a opção de alterar os parâmetros de aluguel de tal carro
     * @param evt seleção do botão "Alterar Informações"
     */
    private void jButtonAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlterarMouseClicked
        Carro c = ListaCarros.listaCarros.get(this.getIndex());
        if (c.isAlugado() == false) {
            
            jPanel1.setVisible(true); 
            jTextFieldDias.setText(Integer.toString(c.getDiasMinimos()));
            jTextFieldDiaria.setText(Double.toString(c.getPrecoDiario()));
            jTextFieldMulta.setText(Double.toString(c.getMultaDiaria()));
        }
        else {
            JOptionPane.showMessageDialog(this, "O carro selecionado está alugado.");
        }
        
    }//GEN-LAST:event_jButtonAlterarMouseClicked

    /**
     * Método que salva as alterações feitas nos parâmetros de aluguel do carro
     * @param evt ato de selecionar o botão "Salvar"
     */
    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        try {
            if (Double.parseDouble(jTextFieldDiaria.getText()) > 0 && Double.parseDouble(jTextFieldDiaria.getText()) < 10000) {
                try {
                    if (Double.parseDouble(jTextFieldMulta.getText()) > 0 && Double.parseDouble(jTextFieldMulta.getText()) < 10000)
                    {
        
                        ListaCarros.listaCarros.get(this.getIndex()).setDiasMinimos(Integer.parseInt(jTextFieldDias.getText()));
                        ListaCarros.listaCarros.get(this.getIndex()).setPreco(Double.parseDouble(jTextFieldDiaria.getText()));
                        ListaCarros.listaCarros.get(this.getIndex()).setMulta(Double.parseDouble(jTextFieldMulta.getText()));
                        ListaCarros listaCarros = new ListaCarros();
                        listaCarros.setVisible(true);
                        dispose();
        }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,"Preço da multa díaria inválido.","Aviso",JOptionPane.WARNING_MESSAGE);
            jTextFieldMulta.setText("");
                }
        } 
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,"Preço do aluguel diário inválido.","Aviso",JOptionPane.WARNING_MESSAGE);
            jTextFieldDiaria.setText("");
        }
    }//GEN-LAST:event_jButtonSalvarMouseClicked

    /**
     * Método que fecha a tela de alteração dos parâmetros de aluguel e abre novamente
     * a tela com a lista de carros
     * @param evt ato de selecionar o botão "Cancelar"
     */
    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseClicked
        ListaCarros listaCarros = new ListaCarros();
        listaCarros.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelarMouseClicked

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
       
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiariaActionPerformed

    /**
     * Método principal da classe OpcoesCarro
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcoesCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcoesCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcoesCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcoesCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcoesCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldDiaria;
    private javax.swing.JTextField jTextFieldDias;
    private javax.swing.JTextField jTextFieldMulta;
    // End of variables declaration//GEN-END:variables
}
