import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Classe que apresenta uma tela para a remoção de carros do sistema, a partir 
 * de seu Renavam
 * 
 * @author Luan
 * @author Matheo
 */
public class RemoverCarro extends javax.swing.JFrame {
    
    private ArrayList<Carro> listaRenavam = new ArrayList<Carro>();
    private DefaultTableModel model;
    private boolean carregada = false;

    /**
     * Método que carrega a tabela com todos os carros da lista "listaRenavam", que
     * contém os carros que possuem Renavam igual ao informado no campo de texto
     */
    private void carregarTabela()
    {
        DefaultTableModel localModel = (DefaultTableModel) tabelaBusca.getModel();
        
        for (Carro C : this.listaRenavam)
        {
            Object[] row = new Object[4];
            row[0] = String.valueOf(C.getMarca());
            row[1] = String.valueOf(C.getModelo());
            row[2] = String.valueOf(C.getCor());
            row[3] = String.valueOf(C.getRenavam());
            localModel.addRow(row);
        }
    }
    
    /**
     * Método que esvazia a tabela apresentada
     */
    private void recarregarTabela()
    {
        DefaultTableModel localModel = (DefaultTableModel) tabelaBusca.getModel();
        localModel.setRowCount(0);
    }
    
    /**
     * Construtor da classe RemoverCarro
     * Creates new form BuscaCarro
     */
    public RemoverCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRenavam = new javax.swing.JTextField();
        try{     javax.swing.text.MaskFormatter renavam = new javax.swing.text.MaskFormatter("#########");     jTextFieldRenavam = new javax.swing.JFormattedTextField(renavam);  }     catch (Exception e){  }
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBusca = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(880, 460));
        setMinimumSize(new java.awt.Dimension(880, 460));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(880, 460));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setText("Renavam:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 100, 80, 14);

        jTextFieldRenavam.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldRenavam.setBorder(null);
        jTextFieldRenavam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRenavamActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRenavam);
        jTextFieldRenavam.setBounds(60, 130, 200, 14);

        jLabel3.setText("Insira o número do Renavam, depois clique em Buscar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 20, 310, 14);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Buscar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 170, 80, 30);

        tabelaBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Cor", "Renavam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaBusca);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(410, 80, 390, 148);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(680, 290, 80, 30);

        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 290, 90, 30);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(60, 150, 200, 20);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 60, 840, 370);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Remoção de carros");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 880, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 880, 460);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que busca os carros na lista de carros que contém o Renavam igual ao informado no
     * campo de texto, e os insere na lista "listaRenavam"
     * @param evt ato de selecionar o botão "Buscar"
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (carregada == false) {
            for (int i = 0; i < ListaCarros.listaCarros.size(); i++)
            {
                if (jTextFieldRenavam.getText().equals(ListaCarros.listaCarros.get(i).getRenavam()))
                {
                    listaRenavam.add(ListaCarros.listaCarros.get(i));
                }
            }
            if (listaRenavam.size() > 0) {
            carregarTabela();
            carregada = true;
            } else {
                JOptionPane.showMessageDialog(this, "Carro não encontrado.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Método que fecha a tela
     * @param evt ato de selecionar o botão "Voltar"
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Método que remove o carro selecionado na tabela da lista de carros
     * @param evt ato de selecionar o botão "Remover"
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int linhaSelecionada = tabelaBusca.getSelectedRow();
        if (tabelaBusca.isRowSelected(linhaSelecionada))
        {
            for (int i = 0; i < ListaCarros.listaCarros.size(); i++)
            {
                if (jTextFieldRenavam.getText().equals(ListaCarros.listaCarros.get(i).getRenavam()))
                {
                    ListaCarros.listaCarros.remove(ListaCarros.listaCarros.get(i));
                    listaRenavam.clear();
                    jTextFieldRenavam.setText("");
                    recarregarTabela();
                    JOptionPane.showMessageDialog(this, "Carro removido com sucesso!");
                    carregada = false;
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldRenavamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRenavamActionPerformed

    }//GEN-LAST:event_jTextFieldRenavamActionPerformed

    /**
     * Método principal da classe RemoverCarro
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldRenavam;
    private javax.swing.JTable tabelaBusca;
    // End of variables declaration//GEN-END:variables
}
