import javax.swing.JOptionPane;

/**
 * Classe que apresenta uma tela para o login no sistema
 *
 * @author Luan
 * @author Matheo
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Construtor da classe TelaLogin
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelImagem = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonAcesso = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/384e0b3361d99d9c370b4037115324b9-icone-de-carro-vintage-plana.png"))); // NOI18N
        jPanel1.add(jLabelImagem);
        jLabelImagem.setBounds(10, 10, 260, 250);

        jPasswordFieldSenha.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldSenha.setBorder(null);
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(320, 150, 130, 30);

        jTextFieldUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldUsuario.setBorder(null);
        jPanel1.add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(320, 70, 130, 30);

        jLabelSenha.setBackground(new java.awt.Color(204, 204, 204));
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha");
        jPanel1.add(jLabelSenha);
        jLabelSenha.setBounds(320, 130, 40, 20);

        jLabelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuário");
        jPanel1.add(jLabelUsuario);
        jLabelUsuario.setBounds(320, 50, 50, 14);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);
        jButtonSair.setBounds(420, 240, 73, 23);

        jButtonAcesso.setText("Acessar");
        jButtonAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAcesso);
        jButtonAcesso.setBounds(320, 240, 90, 23);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(320, 180, 130, 30);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(320, 100, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho_1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 260, 290, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 340);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_sportalgos.jpg"))); // NOI18N
        jLabelFundoLogin.setText("jLabel1");
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 510, 310);

        setSize(new java.awt.Dimension(507, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
    /**
     * Método que confere se as credenciais informadas nos campos de texto conferem
     * com as credenciais de entrada cadastradas no sistema. Em caso afirmativo, 
     * o sistema é aberto. Em caso negativo, a entrada é negada, até as credenciais
     * informadas serem válidas
     * @param evt ato de selecionar o botão "Acessar"
     */
    private void jButtonAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessoActionPerformed
        int flag = 0;
        int senha;
        senha = LeArquivoBin.leArquivoFuncionarios();
        if (senha != 1)
        {
            if (jTextFieldUsuario.getText().equals("admin") && jPasswordFieldSenha.getText().equals("admin")) {
            TelaPrincipal tela = new TelaPrincipal();
            NovaSenha novaTela = new NovaSenha();
            tela.setVisible(true);
            novaTela.setVisible(true);
            
            dispose();
            } else {
                JOptionPane.showMessageDialog(null,"Usuário/senha incorreto(s)","Aviso",JOptionPane.WARNING_MESSAGE);
                jTextFieldUsuario.setText("");
                jPasswordFieldSenha.setText("");
                }
        } else {
            LeArquivoBin.leArquivoClientes();
            LeArquivoBin.leArquivoCarros();
            LeArquivoBin.leArquivoAluguel();
            for (int i = 0; i < ListaFuncionarios.listaFuncionarios.size(); i++)
            {
                if (jTextFieldUsuario.getText().equals(ListaFuncionarios.listaFuncionarios.get(i).getLogin()) && jPasswordFieldSenha.getText().equals(ListaFuncionarios.listaFuncionarios.get(i).getSenha())) {
                    TelaPrincipal tela = new TelaPrincipal();
                    tela.setVisible(true);
                    flag++;
                    dispose();
                    break;                   
                }
            }
            if (flag == 0) {
                JOptionPane.showMessageDialog(null,"Usuário/senha incorreto(s)","Aviso",JOptionPane.WARNING_MESSAGE);
                jTextFieldUsuario.setText("");
                jPasswordFieldSenha.setText("");
                ListaFuncionarios.listaFuncionarios.clear();
                ListaClientes.listaClientes.clear();
                ListaCarros.listaCarros.clear();
            }
        }
    }//GEN-LAST:event_jButtonAcessoActionPerformed

    /**
     * Método que fecha o sistema
     * @param evt ato de selecionar o botão "Sair"
     */
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * Método principal da classe TelaLogin
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcesso;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
