import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;

/**
 * Classe que apresenta uma tela intermediáriia, que oferece opções para
 * acessar as outras telas e funções do sistema
 * 
 * @author Luan
 * @author Matheo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Construtor da classe TelaPrincipal
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");  
        Date date = new Date();
        dia.setText("AlugaCar - " + formatador.format(date));
        jPanelMenu.setVisible(false); 
        jPanelFerramentas.setVisible(false);
        jPanelAlugueis.setVisible(false);
        jPanelCadastros.setVisible(false);
        jPanelAdd.setVisible(false);
        jPanelRemover.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelRemover = new javax.swing.JPanel();
        itemRemoveCliente = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        itemRemoveFuncionario = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        itemRemoveCarro = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelAdd = new javax.swing.JPanel();
        itemAddCliente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        itemAddFuncionario = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        itemAddCarro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelCadastros = new javax.swing.JPanel();
        jPanelAdicionar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelRemove = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelAlugueis = new javax.swing.JPanel();
        itemAdicionar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        itemDevolver = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelFerramentas = new javax.swing.JPanel();
        itemListaClientes = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        itemListaFuncionarios = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        itemListaCarro = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        itemAluguel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        itemCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        itemFerramentas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        itemSair = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dia = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("jMenu10");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLayeredPane1.setBackground(new java.awt.Color(51, 51, 51));
        jLayeredPane1.setForeground(new java.awt.Color(51, 51, 51));

        jPanelRemover.setBackground(new java.awt.Color(51, 51, 51));
        jPanelRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRemoverMouseExited(evt);
            }
        });
        jPanelRemover.setLayout(null);

        itemRemoveCliente.setBackground(new java.awt.Color(255, 153, 51));
        itemRemoveCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemRemoveClienteMouseClicked(evt);
            }
        });
        itemRemoveCliente.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel11.setText("         Cliente");
        itemRemoveCliente.add(jLabel11);
        jLabel11.setBounds(0, 10, 110, 20);

        jPanelRemover.add(itemRemoveCliente);
        itemRemoveCliente.setBounds(30, 70, 110, 40);

        itemRemoveFuncionario.setBackground(new java.awt.Color(255, 153, 51));
        itemRemoveFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemRemoveFuncionarioMouseClicked(evt);
            }
        });
        itemRemoveFuncionario.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel12.setText("      Funcionário");
        itemRemoveFuncionario.add(jLabel12);
        jLabel12.setBounds(0, 0, 90, 40);

        jPanelRemover.add(itemRemoveFuncionario);
        itemRemoveFuncionario.setBounds(30, 160, 110, 40);

        itemRemoveCarro.setBackground(new java.awt.Color(255, 153, 51));
        itemRemoveCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemRemoveCarroMouseClicked(evt);
            }
        });
        itemRemoveCarro.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel13.setText("Carro");
        itemRemoveCarro.add(jLabel13);
        jLabel13.setBounds(39, 13, 30, 15);

        jPanelRemover.add(itemRemoveCarro);
        itemRemoveCarro.setBounds(30, 250, 110, 40);

        jLayeredPane1.add(jPanelRemover);
        jPanelRemover.setBounds(0, 30, 0, 390);

        jPanelAdd.setBackground(new java.awt.Color(51, 51, 51));
        jPanelAdd.setAlignmentX(0.0F);
        jPanelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAddMouseExited(evt);
            }
        });
        jPanelAdd.setLayout(null);

        itemAddCliente.setBackground(new java.awt.Color(255, 153, 51));
        itemAddCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddClienteMouseClicked(evt);
            }
        });
        itemAddCliente.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel8.setText("Cliente");
        itemAddCliente.add(jLabel8);
        jLabel8.setBounds(36, 13, 70, 15);

        jPanelAdd.add(itemAddCliente);
        itemAddCliente.setBounds(30, 80, 109, 40);

        itemAddFuncionario.setBackground(new java.awt.Color(255, 153, 51));
        itemAddFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddFuncionarioMouseClicked(evt);
            }
        });
        itemAddFuncionario.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText("Funcionário");
        itemAddFuncionario.add(jLabel9);
        jLabel9.setBounds(25, 10, 65, 20);

        jPanelAdd.add(itemAddFuncionario);
        itemAddFuncionario.setBounds(30, 170, 110, 40);

        itemAddCarro.setBackground(new java.awt.Color(255, 153, 51));
        itemAddCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddCarroMouseClicked(evt);
            }
        });
        itemAddCarro.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setText("Carro");
        itemAddCarro.add(jLabel10);
        jLabel10.setBounds(40, 10, 30, 20);

        jPanelAdd.add(itemAddCarro);
        itemAddCarro.setBounds(30, 260, 109, 40);

        jLayeredPane1.add(jPanelAdd);
        jPanelAdd.setBounds(0, 30, 0, 390);

        jPanelCadastros.setBackground(new java.awt.Color(51, 51, 51));
        jPanelCadastros.setAlignmentX(0.0F);
        jPanelCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCadastrosMouseExited(evt);
            }
        });
        jPanelCadastros.setLayout(null);

        jPanelAdicionar.setBackground(new java.awt.Color(255, 153, 51));
        jPanelAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAdicionarMouseClicked(evt);
            }
        });
        jPanelAdicionar.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("Adicionar");
        jPanelAdicionar.add(jLabel6);
        jLabel6.setBounds(27, 13, 70, 15);

        jPanelCadastros.add(jPanelAdicionar);
        jPanelAdicionar.setBounds(30, 90, 99, 41);

        jPanelRemove.setBackground(new java.awt.Color(255, 153, 51));
        jPanelRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRemoveMouseClicked(evt);
            }
        });
        jPanelRemove.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("Remover");
        jPanelRemove.add(jLabel7);
        jLabel7.setBounds(28, 13, 70, 15);

        jPanelCadastros.add(jPanelRemove);
        jPanelRemove.setBounds(30, 200, 99, 40);

        jLayeredPane1.add(jPanelCadastros);
        jPanelCadastros.setBounds(0, 30, 0, 390);

        jPanelAlugueis.setBackground(new java.awt.Color(51, 51, 51));
        jPanelAlugueis.setAlignmentX(0.0F);
        jPanelAlugueis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAlugueisMouseExited(evt);
            }
        });
        jPanelAlugueis.setLayout(null);

        itemAdicionar.setBackground(new java.awt.Color(255, 153, 51));
        itemAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAdicionarMouseClicked(evt);
            }
        });
        itemAdicionar.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel14.setText("Adicionar");
        itemAdicionar.add(jLabel14);
        jLabel14.setBounds(30, 10, 60, 20);

        jPanelAlugueis.add(itemAdicionar);
        itemAdicionar.setBounds(30, 100, 110, 40);

        itemDevolver.setBackground(new java.awt.Color(255, 153, 51));
        itemDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemDevolverMouseClicked(evt);
            }
        });
        itemDevolver.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel15.setText("Devolução");
        itemDevolver.add(jLabel15);
        jLabel15.setBounds(26, 10, 60, 20);

        jPanelAlugueis.add(itemDevolver);
        itemDevolver.setBounds(30, 220, 110, 40);

        jLayeredPane1.add(jPanelAlugueis);
        jPanelAlugueis.setBounds(0, 30, 0, 390);

        jPanelFerramentas.setBackground(new java.awt.Color(51, 51, 51));
        jPanelFerramentas.setAlignmentX(0.0F);
        jPanelFerramentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelFerramentasMouseExited(evt);
            }
        });
        jPanelFerramentas.setLayout(null);

        itemListaClientes.setBackground(new java.awt.Color(255, 153, 51));
        itemListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListaClientesMouseClicked(evt);
            }
        });
        itemListaClientes.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel16.setText("Lista de Clientes");
        itemListaClientes.add(jLabel16);
        jLabel16.setBounds(10, 20, 110, 15);

        jPanelFerramentas.add(itemListaClientes);
        itemListaClientes.setBounds(20, 70, 130, 50);

        itemListaFuncionarios.setBackground(new java.awt.Color(255, 153, 51));
        itemListaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListaFuncionariosMouseClicked(evt);
            }
        });
        itemListaFuncionarios.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel17.setText("Lista de Funcionários");
        itemListaFuncionarios.add(jLabel17);
        jLabel17.setBounds(10, 5, 150, 40);

        jPanelFerramentas.add(itemListaFuncionarios);
        itemListaFuncionarios.setBounds(20, 150, 130, 50);

        itemListaCarro.setBackground(new java.awt.Color(255, 153, 51));
        itemListaCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListaCarroMouseClicked(evt);
            }
        });
        itemListaCarro.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel18.setText("Lista de Carros");
        itemListaCarro.add(jLabel18);
        jLabel18.setBounds(10, 20, 110, 10);

        jPanelFerramentas.add(itemListaCarro);
        itemListaCarro.setBounds(20, 230, 130, 50);

        jLayeredPane1.add(jPanelFerramentas);
        jPanelFerramentas.setBounds(0, 30, 0, 390);

        jPanelMenu.setBackground(new java.awt.Color(51, 51, 51));
        jPanelMenu.setAlignmentX(0.0F);
        jPanelMenu.setMaximumSize(new java.awt.Dimension(32767, 470));
        jPanelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenuMouseExited(evt);
            }
        });
        jPanelMenu.setLayout(null);

        itemAluguel.setBackground(new java.awt.Color(255, 153, 51));
        itemAluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAluguelMouseClicked(evt);
            }
        });
        itemAluguel.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 102, 0));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Alugueis");
        itemAluguel.add(jLabel3);
        jLabel3.setBounds(32, 13, 70, 15);

        jPanelMenu.add(itemAluguel);
        itemAluguel.setBounds(30, 130, 110, 40);

        itemCadastro.setBackground(new java.awt.Color(255, 153, 51));
        itemCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemCadastroMouseClicked(evt);
            }
        });
        itemCadastro.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Cadastros");
        itemCadastro.add(jLabel1);
        jLabel1.setBounds(27, 13, 80, 15);

        jPanelMenu.add(itemCadastro);
        itemCadastro.setBounds(28, 56, 110, 40);

        itemFerramentas.setBackground(new java.awt.Color(255, 153, 51));
        itemFerramentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemFerramentasMouseClicked(evt);
            }
        });
        itemFerramentas.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Ferramentas");
        itemFerramentas.add(jLabel4);
        jLabel4.setBounds(22, 13, 90, 15);

        jPanelMenu.add(itemFerramentas);
        itemFerramentas.setBounds(30, 200, 110, 40);

        itemSair.setBackground(new java.awt.Color(255, 153, 51));
        itemSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSairMouseClicked(evt);
            }
        });
        itemSair.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Sair");
        itemSair.add(jLabel5);
        jLabel5.setBounds(42, 13, 50, 15);

        jPanelMenu.add(itemSair);
        itemSair.setBounds(28, 316, 110, 40);

        jLayeredPane1.add(jPanelMenu);
        jPanelMenu.setBounds(0, 30, 0, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 30, 36, 34);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setAlignmentX(0.0F);

        dia.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/384e0b3361d99d9c370b4037115324b9-icone-de-carro-vintage-plana.png"))); // NOI18N
        jLayeredPane1.add(jLabel19);
        jLabel19.setBounds(250, 60, 290, 290);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho.png"))); // NOI18N
        jLayeredPane1.add(jLabel20);
        jLabel20.setBounds(230, 340, 330, 70);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(609, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que abre o menu principal com as opções "Cadastros", "Alugueis", "Ferramentas" e "Sair"
     * @param evt ato de entrar com o mouse no ícone do canto superior esquerdo
     */
    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
         jPanelMenu.setVisible(true);
         jLabel2.setVisible(false);  
            Thread th = new Thread(){
                public void run(){

                    try{
                        for(int comp = 1; comp <= 167; comp++){           
                            Thread.sleep(1);
                            if(jPanelMenu.getWidth() <= 167){
                                jPanelMenu.setBounds(0,0,comp, 442);
                            }
                        }

                    }catch(Exception e){}
                }
        };th.start();
        
    }//GEN-LAST:event_jLabel2MouseEntered

    /**
     * Método que fecha o menu principal
     * @param evt ato de sair, com o mouse, da área do menu
     */
    private void jPanelMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuMouseExited
        java.awt.Point p = new java.awt.Point(evt.getLocationOnScreen());
        SwingUtilities.convertPointFromScreen(p, evt.getComponent());
        if(evt.getComponent().contains(p)) {
            return;
        }else{
            if(jPanelMenu.getWidth() == 167){
                Thread th = new Thread(){
                    public void run(){
                        try{
                            for(int comp = 167; comp >= 0; comp--){
                                Thread.sleep(1);
                                jPanelMenu.setBounds(0,0,comp, 442);
                                if(comp == 0){
                                    jLabel2.setVisible(true);
                                    jPanelMenu.setVisible(false);
                                }
                            }    
                        }catch(Exception e){}
                    }
                };th.start();               
            }
        }
    }//GEN-LAST:event_jPanelMenuMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
           
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * Método que escreve os arquivos binários contendo as informações 
     * dos clientes, carros, funcionários e alugueis que foram inseridos no sistema.
     * @param evt ato de selecionar o botão "Sair".
     */
    private void itemSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSairMouseClicked
        GeraArquivoBin.geraCarros();
        GeraArquivoBin.geraCliente();
        GeraArquivoBin.geraFuncionario();
        GeraArquivoBin.geraAluguel();
        System.exit(0);
    }//GEN-LAST:event_itemSairMouseClicked

    /**
     * Método que abre o menu de cadastros, com as opções "Adicionar" e "Remover".
     * @param evt ato de selecionar o botão "Cadastros".
     */
    private void itemCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCadastroMouseClicked
       jLabel2.setVisible(false); 
       jPanelCadastros.setVisible(true);
        Thread th = new Thread(){
            public void run(){
                try{
                    for(int comp = 1; comp <= 167; comp++){           
                        Thread.sleep(1);
                        if(jPanelCadastros.getWidth() <= 167){
                            jPanelCadastros.setBounds(0,0,comp, 442);
                        }
                    }
                }catch(Exception e){}
            }
        };th.start();
        jPanelMenu.setBounds(0,0,0,442);       
           
    }//GEN-LAST:event_itemCadastroMouseClicked

    /**
     * Método que abre o menu para adições ao sistema, dando as opções de adicionar um cliente, 
     * funcionário ou carro.
     * @param evt ato de selecionar o botão "Adicionar".
     */
    private void jPanelAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAdicionarMouseClicked
        jLabel2.setVisible(false); 
        jPanelAdd.setVisible(true);
        Thread th = new Thread(){
            public void run(){
                try{
                    for(int comp = 1; comp <= 167; comp++){           
                        Thread.sleep(1);
                        if(jPanelAdd.getWidth() <= 167){
                            jPanelAdd.setBounds(0,0,comp, 442);
                        }
                    }
                }catch(Exception e){}
            }
        };th.start();
        jPanelCadastros.setBounds(0,0,0, 442);
        jPanelCadastros.setVisible(false);
    }//GEN-LAST:event_jPanelAdicionarMouseClicked

    /**
     * Método que abre a tela para o cadastro de clientes
     * @param evt ato de selecionar o botão "Cadastros", "Adicionar" e depois "Cliente" 
     */
    private void itemAddClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddClienteMouseClicked
        FormularioCliente FormCliente = new FormularioCliente();
        FormCliente.setVisible(true);
    }//GEN-LAST:event_itemAddClienteMouseClicked

    /**
     * Método que abre a tela para o cadastro de funcionários
     * @param evt ato de selecionar o botão "Cadastros", "Adicionar" e depois "Funcionário" 
     */
    private void itemAddFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddFuncionarioMouseClicked
        FormularioFuncionario formulario = new FormularioFuncionario();
        formulario.setVisible(true);
    }//GEN-LAST:event_itemAddFuncionarioMouseClicked

    /**
     * Método que abre a tela para o cadastro de carros
     * @param evt ato de selecionar o botão "Cadastros", "Adicionar" e depois "Carros" 
     */
    private void itemAddCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddCarroMouseClicked
        FormularioCarro tela = new FormularioCarro();
        tela.setVisible(true);
    }//GEN-LAST:event_itemAddCarroMouseClicked

    /**
     * Método que abre a tela para a remoção de clientes
     * @param evt ato de selecionar o botão "Cadastros", "Remover" e depois "Cliente" 
     */
    private void itemRemoveClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemRemoveClienteMouseClicked
        RemoverCliente tela = new RemoverCliente();
        tela.setVisible(true);
    }//GEN-LAST:event_itemRemoveClienteMouseClicked

    /**
     * Método que abre a tela para a remoção de funcionários
     * @param evt ato de selecionar o botão "Cadastros", "Remover" e depois "Funcionário" 
     */
    private void itemRemoveFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemRemoveFuncionarioMouseClicked
        RemoverFuncionario remover = new RemoverFuncionario();
        remover.setVisible(true);
    }//GEN-LAST:event_itemRemoveFuncionarioMouseClicked

    /**
     * Método que abre a tela para a remoção de carros
     * @param evt ato de selecionar o botão "Cadastros", "Remover" e depois "Carro" 
     */
    private void itemRemoveCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemRemoveCarroMouseClicked
        RemoverCarro tela = new RemoverCarro();
        tela.setVisible(true);
    }//GEN-LAST:event_itemRemoveCarroMouseClicked

    /**
     * Método que abre o menu para remoções do sistema, dando as opções de remover um cliente, 
     * funcionário ou carro.
     * @param evt ato de selecionar o botão "Remover".
     */
    private void jPanelRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoveMouseClicked
        jLabel2.setVisible(false);
        jPanelRemover.setVisible(true);
        Thread th = new Thread(){
            public void run(){
                try{
                    for(int comp = 1; comp <= 167; comp++){           
                        Thread.sleep(1);
                        if(jPanelRemover.getWidth() <= 167){
                            jPanelRemover.setBounds(0,0,comp, 442);
                        }
                    }
                }catch(Exception e){}
            }
        };th.start();
        jPanelCadastros.setBounds(0,0,0,442);
    }//GEN-LAST:event_jPanelRemoveMouseClicked

    /**
     * Método que fecha o menu principal.
     * @param evt ato de sair, com o mouse, da área do menu.
     */
    private void jPanelCadastrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCadastrosMouseExited
        java.awt.Point p = new java.awt.Point(evt.getLocationOnScreen());
        SwingUtilities.convertPointFromScreen(p, evt.getComponent());
        if(evt.getComponent().contains(p)) {
            return;
        }else{
            if(jPanelCadastros.getWidth() == 167){
                Thread th = new Thread(){
                    public void run(){

                        try{
                            for(int comp = 167; comp >= 0; comp--){
                                Thread.sleep(1);
                                
                                jPanelCadastros.setBounds(0,0,comp,442);
                                if(comp == 0){
                                    jLabel2.setVisible(true);
                                    jPanelCadastros.setVisible(false);
                                }
                                
                            }    
                        }catch(Exception e){}
                    }
                };th.start();               
            }
        }
    }//GEN-LAST:event_jPanelCadastrosMouseExited

    /**
     * Método que fecha o menu principal.
     * @param evt ato de sair, com o mouse, da área do menu
     */
    private void jPanelAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddMouseExited
        java.awt.Point p = new java.awt.Point(evt.getLocationOnScreen());
        SwingUtilities.convertPointFromScreen(p, evt.getComponent());
        if(evt.getComponent().contains(p)) {
            return;
        }else{
            if(jPanelAdd.getWidth() == 167){
                Thread th = new Thread(){
                    public void run(){

                        try{
                            for(int comp = 167; comp >= 0; comp--){
                                Thread.sleep(1);
                                jPanelAdd.setBounds(0,0,comp,442); 
                                
                                if(comp == 0){
                                    jLabel2.setVisible(true);
                                    jPanelAdd.setVisible(false);
                                }
                            }    
                        }catch(Exception e){}
                    }
                };th.start();             
            }
        }
    }//GEN-LAST:event_jPanelAddMouseExited

    /**
     * Método que fecha o menu principal
     * @param evt ato de sair, com o mouse, da área do menu
     */
    private void jPanelRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoverMouseExited
        java.awt.Point p = new java.awt.Point(evt.getLocationOnScreen());
        SwingUtilities.convertPointFromScreen(p, evt.getComponent());
        if(evt.getComponent().contains(p)) {
            return;
        }else{
            if(jPanelRemover.getWidth() == 167){
                Thread th = new Thread(){
                    public void run(){

                        try{
                            for(int comp = 167; comp >= 0; comp--){
                                Thread.sleep(1);
                                
                                jPanelRemover.setBounds(0,0,comp,442);
                                if(comp == 0){
                                    jLabel2.setVisible(true);
                                    jPanelRemover.setVisible(false);
                                }
                            }
                               
                        }catch(Exception e){}
                    }
                };th.start();           
            }
        }
    }//GEN-LAST:event_jPanelRemoverMouseExited

    /**
     * Método que abre o menu de alugueis, com as opções de efetuar um aluguel ou
     * encerrar um aluguel (devolução)
     * @param evt ato de selecionar o botão "Alugueis"
     */
    private void itemAluguelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAluguelMouseClicked
        jLabel2.setVisible(false);
        jPanelAlugueis.setVisible(true);
        Thread th = new Thread(){
            public void run(){

                try{
                    for(int comp = 1; comp <= 167; comp++){           
                        Thread.sleep(1);
                        if(jPanelAlugueis.getWidth() <= 167){
                            jPanelAlugueis.setBounds(0,0,comp, 442);
                        }
                    }

                }catch(Exception e){}
            }
        
        };th.start();
        jPanelMenu.setBounds(0,0,0,442);   
    }//GEN-LAST:event_itemAluguelMouseClicked

    /**
     * Método que fecha o menu principal
     * @param evt ato de sair, com o mouse, da área do menu
     */
    private void jPanelAlugueisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlugueisMouseExited
        java.awt.Point p = new java.awt.Point(evt.getLocationOnScreen());
        SwingUtilities.convertPointFromScreen(p, evt.getComponent());
        if(evt.getComponent().contains(p)) {
            return;
        }else{
            if(jPanelAlugueis.getWidth() == 167){
                Thread th = new Thread(){
                    public void run(){

                        try{
                            for(int comp = 167; comp >= 0; comp--){
                                Thread.sleep(1);
                                
                                jPanelAlugueis.setBounds(0,0,comp,442);
                                if(comp == 0){
                                    jLabel2.setVisible(true);
                                    jPanelAlugueis.setVisible(false);
                                }
                                
                            }    
                        }catch(Exception e){}
                    }
                };th.start();
            }
        }
    }//GEN-LAST:event_jPanelAlugueisMouseExited

    /**
     * Método que abre a tela contendo a tabela com os carros não alugados, 
     * para o aluguel dos mesmos
     * @param evt ato de selecionar o botão "Alugueis" e depois "Adicionar"
     */
    private void itemAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAdicionarMouseClicked
        ListaCarrosParaAluguel tela = new ListaCarrosParaAluguel();
        tela.setVisible(true);
    }//GEN-LAST:event_itemAdicionarMouseClicked

    /**
     * Método que abre a tela para a devolução do carro alugado
     * @param evt ato de selecionar o botão "Alugueis" e depois "Devolução"
     */
    private void itemDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDevolverMouseClicked
        try{
            ListaAlugueis telaDevol = new ListaAlugueis();
            telaDevol.setVisible(true);
        }catch(Exception e){System.err.println(e);}
    }//GEN-LAST:event_itemDevolverMouseClicked

    /**
     * Método que abre o menu de ferramentas, com as opções de abrir uma lista 
     * com todos os funcionários, com todos os clientes ou com todos os carros cadastrados
     * no sistema.
     * @param evt ato de selecionar o botão "Ferramentas" no menu principal
     */
    private void itemFerramentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemFerramentasMouseClicked
        jLabel2.setVisible(false);
        jPanelFerramentas.setVisible(true);
        Thread th = new Thread(){
            public void run(){

                try{
                    for(int comp = 1; comp <= 167; comp++){           
                        Thread.sleep(1);
                        if(jPanelFerramentas.getWidth() <= 167){
                            jPanelFerramentas.setBounds(0,0,comp, 442);
                        }
                    }

                }catch(Exception e){}
            }
        
        };th.start();
        jPanelMenu.setBounds(0,0,0,442);   
        
    }//GEN-LAST:event_itemFerramentasMouseClicked

    /**
     * Método que fecha o menu principal
     * @param evt ato de sair, com o mouse, da área do menu
     */
    private void jPanelFerramentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFerramentasMouseExited
        java.awt.Point p = new java.awt.Point(evt.getLocationOnScreen());
        SwingUtilities.convertPointFromScreen(p, evt.getComponent());
        if(evt.getComponent().contains(p)) {
            return;
        }else{
            if(jPanelFerramentas.getWidth() == 167){
                Thread th = new Thread(){
                    public void run(){

                        try{
                            for(int comp = 167; comp >= 0; comp--){
                                Thread.sleep(1);
                                
                                jPanelFerramentas.setBounds(0,0,comp,442);
                                if(comp == 0){
                                    jLabel2.setVisible(true);
                                    jPanelFerramentas.setVisible(false);
                                }
                                
                            }    
                        }catch(Exception e){}
                    }
                };th.start();
            }
        }
    }//GEN-LAST:event_jPanelFerramentasMouseExited

    /**
     * Método que abre a tela que contém a tabela com todos os clientes cadastrados
     * @param evt ato de selecionar o botão "Ferramentas" e depois "Lista de Clientes"
     */
    private void itemListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListaClientesMouseClicked
        ListaClientes listaCliente = new ListaClientes();
        listaCliente.setVisible(true);
    }//GEN-LAST:event_itemListaClientesMouseClicked

    /**
     * Método que abre a tela que contém a tabela com todos os funcionários cadastrados
     * @param evt ato de selecionar o botão "Ferramentas" e depois "Lista de Funcionários"
     */
    private void itemListaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListaFuncionariosMouseClicked
        ListaFuncionarios tela = new ListaFuncionarios();
        tela.setVisible(true);
    }//GEN-LAST:event_itemListaFuncionariosMouseClicked

    /**
     * Método que abre a tela que contém a tabela com todos os carros cadastrados
     * @param evt ato de selecionar o botão "Ferramentas" e depois "Lista de Carros"
     */
    private void itemListaCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListaCarroMouseClicked
        ListaCarros tela = new ListaCarros();
        tela.setVisible(true);
    }//GEN-LAST:event_itemListaCarroMouseClicked

    /**
     * Método principal da classe TelaPrincipal
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dia;
    private javax.swing.JPanel itemAddCarro;
    private javax.swing.JPanel itemAddCliente;
    private javax.swing.JPanel itemAddFuncionario;
    private javax.swing.JPanel itemAdicionar;
    private javax.swing.JPanel itemAluguel;
    private javax.swing.JPanel itemCadastro;
    private javax.swing.JPanel itemDevolver;
    private javax.swing.JPanel itemFerramentas;
    private javax.swing.JPanel itemListaCarro;
    private javax.swing.JPanel itemListaClientes;
    private javax.swing.JPanel itemListaFuncionarios;
    private javax.swing.JPanel itemRemoveCarro;
    private javax.swing.JPanel itemRemoveCliente;
    private javax.swing.JPanel itemRemoveFuncionario;
    private javax.swing.JPanel itemSair;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelAdicionar;
    private javax.swing.JPanel jPanelAlugueis;
    private javax.swing.JPanel jPanelCadastros;
    private javax.swing.JPanel jPanelFerramentas;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelRemove;
    private javax.swing.JPanel jPanelRemover;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
